### PR TITLE
ROC-2832: updated xlsx file

### PR DESCRIPTION
**Pull request by yarpo**
### JIRA link ###
https://tools.hmcts.net/jira/browse/ROC-2832

### Change description ###
Updated xlsx file and added new role

**Does this PR introduce a breaking change?** (check one with "x")

```
[x] Yes
[ ] No
```

### CODE REVIEW

**Comment by timja-kainos** [comment]
What have you updated and is the spreadsheet on the google doc up to date?

**Comment by yarpo** [comment]
@timja-kainos I have added new event 

```
MoneyClaimCase | MigrationFromClaimstoreEvent | caseworker-cmc-systemupdate | CRUD
```

No, I haven't updated google doc yet. I want someone to double check everything is OK.

**Comment by timja-kainos** [comment]
Please update the google doc

**Comment by yarpo** [comment]
@timja-kainos updated. Is there anything else you want me to do before you add :+1: ?

**Comment by yarpo** [comment]
@sabahirfan - xlsx updated.

**Pull request merged**
