### PR TITLE
ROC-3800: Setup scheduler database

### PR DESCRIPTION
**Pull request by dharmendrak**
### JIRA link ###
https://tools.hmcts.net/jira/browse/ROC-3800

### CODE REVIEW

**Comment by sabahirfan** [comment]
As we are using `CONNECTION LIMIT = -1` while creating databases which means `no limit`. so I think we are safe.

**Comment by timja-kainos** [comment]
There’s a Postgres max_connections server default of 100 is that overridden by the create dB command?

**Comment by timja-kainos** [comment]
https://www.postgresql.org/docs/current/static/runtime-config-connection.html#GUC-MAX-CONNECTIONS

**Comment by timja-kainos** [comment]
Superseded by https://github.com/hmcts/cmc-integration-tests/pull/194
The max_connections is overridden as a command line argument to postgres startup so it would have been fine,
but we are using a different postgres version for our new cnp database so have added another container for it

**Pull request closed without merging**
